export enum LocationInsightCategory {
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  PLANNED_PROJECT = 'PLANNED_PROJECT',
  SOCIO_ECONOMIC = 'SOCIO_ECONOMIC',
  POLICY = 'POLICY',
  DEVELOPMENT = 'DEVELOPMENT',
  OTHER = 'OTHER',
}
