export enum ParcelFacilityType {
  HOSPITAL = 'HOSPITAL',
  CLINIC = 'CLINIC',
  SCHOOL = 'SCHOOL',
  UNIVERSITY = 'UNIVERSITY',
  PUBLIC_TRANSPORT = 'PUBLIC_TRANSPORT',
  POLICE = 'POLICE',
  FIRE_STATION = 'FIRE_STATION',
  MARKET = 'MARKET',
  GOVERNMENT = 'GOVERNMENT',
  PARK = 'PARK',
  WATER_POINT = 'WATER_POINT',
  OTHER = 'OTHER',
}
