export enum ParcelRiskMetric {
  ELEVATION = 'ELEVATION',
  SLOPE = 'SLOPE',
  FLOOD_RISK = 'FLOOD_RISK',
  DROUGHT_RISK = 'DROUGHT_RISK',
  TEMPERATURE = 'TEMPERATURE',
  RAINFALL = 'RAINFALL',
  SEA_LEVEL = 'SEA_LEVEL',
  SEISMIC = 'SEISMIC',
  CLIMATE_VULNERABILITY = 'CLIMATE_VULNERABILITY',
  INFRASTRUCTURE_ACCESS = 'INFRASTRUCTURE_ACCESS',
  CUSTOM = 'CUSTOM',
}

